### ISSUE TITLE
Datepicker doesn't work properly when user has non-standard date format

### ISSUE THREAD

**Issue by jikamens** [jikamens/send-later#17]
See https://bugzilla.mozilla.org/show_bug.cgi?id=799906 .

Also this report from a Send Later user today:

>Running under Thunderbird 52.7.0,, Windows 10.  Using the New Zealand Locale (Date format = dd/mm/yyyy).
>
>Opening send later displays this:
>
>![sendlater](https://user-images.githubusercontent.com/1598067/39263470-3d2a32f8-4890-11e8-9745-652334950610.png)
>
>Unable to use the date/time picker in the second line.  
>
>Seems like it is some kind of  date format conflict.

**Comment by jikquantopian** [comment]
N.B. bug 799906 in Mozilla is _not_ the same as the bug reported here. I'm not sure why I linked to it above, it really is a different bug.
