### ISSUE TITLE
Thunderbird 60.9.0

### ISSUE THREAD

**Issue by jsrobinson** [jikamens/send-later#26]
Just posted this in the Thunderbird Addons thoughts are but not sure I will see notifications for replies

Thunderbird 60.9.0 is complaining that Send Later isn’t compatible, I forced extension.CheckCompat and got the xpi to install, but File->Send Later doesn’t evoke your dialog, it just puts the message in the outbox. I donated many years ago, but willing to re-up to help get this fixed! Thank you for such an awesome plugin!

**Comment by jikamens** [comment]
The current version of Send Later only works with TB68+. If you want to use Send Later with TB60, you need [version 6.4.6](https://addons.thunderbird.net/en-US/thunderbird/addon/send-later-3/versions/6.4.6).

**Comment by jsrobinson** [comment]
I feel like a noob. Sorry about that!
