### ISSUE TITLE
Add-On doesn't work on TB78

### ISSUE THREAD

**Issue by maherma-adg** [jikamens/send-later#33]
After update to TB78 add-on is not working. 

Install it again is impossible due this error:

 ```
Add-on sendlater3@kamens.us is not compatible with application version. add-on minVersion: 68.0a1. add-on maxVersion: 71.*.
```
Manuel

**Comment by jikamens** [comment]
Please see https://groups.google.com/forum/#!msg/send-later-users/y4WBzYo260E/D6RwuSyBDgAJ .
Note the updated download link in the reply at the bottom.

**Comment by maherma-adg** [comment]
Thank you. I'll follow the new repo.
