### ISSUE TITLE
Is extensions.sendlater3.senddrafts still honoured?

### ISSUE THREAD

**Issue by ribz** [jikamens/send-later#34]
Hi,

I've written some software to send my emails server-side. I've got "extensions.sendlater3.senddrafts" set to false, however Send Later is still sending the emails. Does the extensions.sendlater3.senddrafts setting still work in the latest version?

Ed

**Comment by jikamens** [comment]
Github issues is for bug reports, not support.

Please email me at jik@kamens.us for questions about Send Later in TB68 or Jonathan Perry-Houts at jph@extended-thunder.org for questions about Send Later in TB78.

**Comment by ribz** [comment]
In that case, I'll phase it as a bug report.

Documentation for TB78, https://blog.kamens.us/send-later/, states:

"If you set the preference “extensions.sendlater3.senddrafts” to false in the advanced config editor (described above), then Send Later won’t deliver scheduled drafts when their time comes; it’ll just leave them in your Drafts folder "

However, I've got it set to false and Send Later is still delivering drafts.

Either the documentation or the extension is buggy.

**Comment by ribz** [comment]
Unless that is the documentation for TB68, in which case the heading at the top is confusing.
