### ISSUE TITLE
Performance problems

### ISSUE THREAD

**Issue by fremoikaner** [jikamens/send-later#35]
Hi all!
At first a big "thanks" to bring this useful extension to a new level.
I encounter massive performance issues when send-later is enabled. It uses around 12-15% CPU-usage and is slowing down more and more from hour to hour. A restart helps for a little while but after some hours it's almost impossible to work with TB.
When I disable send-later the CPU-usage drops directly to 1%. enabling it and it has again the high CPU-usage again.
As the complete mail-folder is about 90 GB(!) I started also some other helpful tipps (e.g. disabling the hardware-acceleration, etc.) and also deleted all MSF-files but the problem still persists.

My config:
OS: Win7(64-Bit), TB 78.6.0 (32-Bit)
If you need some more details just let me know which.

Thanks in advance and have a Merry Christmas and a Happy New Year (hopefully better than the old one was ...)
Andreas

**Comment by jikamens** [comment]
Please report this over at https://github.com/Extended-Thunder/send-later/issues. This repository is just for the old, pre-Thunderbird-78 version of Send Later.
