### ISSUE TITLE
"Send" delays messages by __ minutes option Fails Occasionally

### ISSUE THREAD

**Issue by epsso** [jikamens/send-later#37]
I am using TB 91.2.0 (64-bit) and Send Later 9.0.6 and the "Send" delays messages by __ minutes option.

Occasionally when Send Later places multiple copies of a message in the drafts folder and then hangs on the "Copy Complete" dialog box.  The only way out is to close the message that you just clicked on the send button for.  Then, when you click Send the messages are sent immediately instead of going though send later.  

I can reproduce the issue even when Send Later is the only extension running.  I can not repeat the issue when not using the "Send" delays messages by __ minutes option.

I have attached a copy of the web developer console.  There is a "NotAllowedError: Could not remove the file at" error on line 32 that appears to be the beginning of the issue.

[Thunderbird console.txt](https://github.com/jikamens/send-later/files/7382591/Thunderbird.console.txt)

**Comment by epsso** [comment]
Well I was mistaken.  The issue also occurs when you click the "Send" button while the "Send" does "Send Later" option is selected.  TB does not launch Send Later but rather immediately sends the message.  So far, I have not been able to make Send Later fail when clicking on "Send Later" to send the message.

**Comment by jikamens** [comment]
Please report at https://github.com/Extended-Thunder/send-later/issues. This repository is no longer the canonical source for the add-on and is no longer actively maintained.
