### ISSUE TITLE
Defaults should be set in the preferences tab as well as updateable in the dialog

### ISSUE THREAD

**Issue by jamesquilty** [jikamens/send-later#38]
I really appreciate the utility of Send Later and use per-year dynamic scheduling functions`BusinessHours202X` for maximum flexibility. This means that at the beginning of the year I have to:

1. add this year's `BusinessHours202X` function in the Send Later preferences tab and
1. create a "dummy" email and trigger Send Later to access the dialog to change the default dynamic function to `BusinessHours202X`.

As I have 3 separate machines, I have to do this manual process multiple times. It's error-prone and time-consuming.

Ideally, I'd have a single function file, under version control, which Send Later accesses via an alias (symlink) placed in `<path to TB profile>/sendlater3/ufuncs/` so that I could set this _once_ and then update the dynamic function directly from version control. I do this with my signature file, and it works really well for me, but it seems that Send Later wraps dynamic functions into a JSON string which complicates matters.

Second-best, I'd like to eliminate step 2, above, because it involves a lot of GUI work to set something that, I feel, should be able to be set in the preferences tab opened in step 1.

I propose that the Send Later dialog defaults shown in <https://extended-thunder.github.io/send-later/#basic-usage> should be accessible from the preferences tab &mdash; this would make _all_ of the defaults accessible in one place instead of distributed across different places in the GUI. The dialog wouldn't even need to change, it's quite appropriate for it to allow the defaults to be changed and updated.

I hope this sounds like a sensible proposal?

**Comment by jikamens** [comment]
This repository is no longer maintained. Please file this over at https://github.com/Extended-Thunder/send-later/issues

**Comment by jamesquilty** [comment]
Raised as <https://github.com/Extended-Thunder/send-later/issues/421>.
